### ISSUE TITLE
Update Yagna version

### ISSUE THREAD

**Issue by cmdntd** [alexandre-abrioux/golem-node#37]
It seems need for updating Yagna version faster
Could you have a parameter to update/choose Yagna version manually?

**Comment by alexandre-abrioux** [comment]
Hi!

This repository contains a daily check for new Yagna versions, see the workflow:
https://github.com/alexandre-abrioux/golem-node/actions/workflows/update.yaml
The latest version is currently [v0.12.3](https://github.com/golemfactory/yagna/releases/tag/v0.12.3), as we ignore Yagna pre-releases.

If you wish to do otherwise, you can build the Docker image on your local environment:
- clone the repository
- make your adjustments to [`docker/Dockerfile`](https://github.com/alexandre-abrioux/golem-node/blob/master/docker/Dockerfile)
- build the image with [`docker build`](https://docs.docker.com/engine/reference/commandline/build/)
- use this local image instead of `aabrioux/golem-node` in the [docker-compose.yml](https://github.com/alexandre-abrioux/golem-node/blob/574d565db574b5de74edcc1d57fd7258639edab5/docker-compose.yml#L7) file
