### ISSUE TITLE
Transfer ownership to the Golem Factory

### ISSUE THREAD

**Issue by alexandre-abrioux** [alexandre-abrioux/golem-node#6]
I'm opening this issue to discuss the topic of transferring ownership of this repository to the [Golem Factory](https://github.com/golemfactory) as I think it would make sense.

I would be glad to continue maintaining this project. I think we can still find ways to improve it, like maybe adding some CI to automatically follow [Yagna](https://github.com/golemfactory/yagna) releases, or other features I didn't think about yet. I would love being able to help the Golem team in bringing those new features as I will also benefit from them.

But in the end it would make sense, in my opinion, if the repository was owned by the organization. Doing so will allow the Golem team to bring changes to the code that reflects the direction they choose for the growth of the Golem project as a whole.

Tell me what you think :)

see. [Related Github documentation](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

**Comment by cryptobench** [comment]
Hi Alexandre! 

I'm glad that you're reaching out and asking for our opinion on the topic!
Internally on our team we have a lot of projects right now going on, so ideally we would probably prefer if this stayed a community built project just to have less projects to keep maintaining ourselves. Your project is awesome and we of course do want to showcase community built projects, so we have actually launched a revamped version of our website recently, and it includes a page where we plan to showcase projects built for Golem monthly [here](https://www.golem.network/community) ! 
The new website isn't finished yet but we figured we might as well use the momentum that the project currently has, and launch a new website about Yagna rather than have an old outdated one only mentioning Clay Golem. So new things will come and pages will be more refined over time.

You seem to be very good at DevOps and I think that you would personally shine on this project, so I think it would be sad to transfer the ownership to us and not let you have the credit of owning the repository. Hopefully being showcased on our community page could bring you value in your professional career also!

**Comment by alexandre-abrioux** [comment]
Hi @cryptobench ! Thank you for taking the time to answer me and for the kind words.

I completely understand your point as it might be too much for Golem to handle the growing main repository + all the side projects that the community is creating.

I will close this issue for now but do not hesitate reach out in the future. If your team wishes one day to release an official Docker image for New Golem I would be happy to handover the ownership while continuing to contribute.

Just saw the [awesome-golem](https://github.com/golemfactory/awesome-golem/) repo, very cool :) Thanks

**Comment by cryptobench** [comment]
Thanks for the opportunity for a possible future handover, it's much appreciated! I just updated the **awesome-golem** repo with Alpha 4 compatibility for your project just now. 

Thanks for merging!

**Comment by lerenn** [comment]
As a new user of Golem and already user of Ansible+Docker, it was quite uneasy to find an image like this one, as it is not official.

The argumentation against integrating it now makes sense, but I wanted to add my support for this image integration :)

Keep up the good work guys ! 
You're amazing !
